services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        deploy:
            resources:
                limits:
                    cpus: "2.0"
        ports:
            - "8000:8000"
            - "8080:8080"
        volumes:
            - ./backend:/app
            - backend-vendor:/app/vendor
        depends_on:
            - mysql-db
            - redis
            - elasticsearch
            - rabbitmq
            - prometheus
        networks:
            - app

    mysql-db:
        image: mysql:8.3
        environment:
            MYSQL_DATABASE: inspirelink
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: rootpassword
        ports:
            - "3306:3306"
        volumes:
            - sql-data:/var/lib/mysql
        restart: unless-stopped
        networks:
            - app

    redis:
        image: redis:7.2.3
        command: redis-server /etc/redis/redis.conf
        ports:
            - 6379:6379
        volumes:
            - ./redis/redis.conf:/etc/redis/redis.conf
        restart: unless-stopped
        networks:
            - app

    rabbitmq:
        image: rabbitmq:3.9-management
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=rmuser
            - RABBITMQ_DEFAULT_PASS=rmpassword
            - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 107374182 # 100 MB
        volumes:
            - rabbitmq:/var/lib/rabbitmq
        ports:
            - 15672:15672
            - 5672:5672
        networks:
            - app

    elasticsearch:
        image: elasticsearch:8.10.1
        volumes:
            - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        environment:
            - "discovery.type=single-node"
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - "indices.memory.index_buffer_size=20%"
        deploy:
            resources:
                limits:
                    cpus: "1.0"
        ports:
            - 9200:9200
            - 9300:9300
        restart: unless-stopped
        networks:
            - app

    prometheus:
        image: prom/prometheus
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090
        restart: unless-stopped
        networks:
            - app

networks:
    app:
        driver: bridge

volumes:
    sql-data:
    backend-vendor:
    rabbitmq:
