services:
    main-service:
        build:
            context: ./services/main-service
            dockerfile: Dockerfile
        deploy:
            resources:
                limits:
                    cpus: "2.0"
        ports:
            - "8000:8000"
        volumes:
            - ./services/main-service:/app
            - main-service-vendor:/app/vendor
        depends_on:
            - mysql-db
            - redis
            - elasticsearch
            - kafka
            - prometheus
        networks:
            - app

    mysql-db:
        image: mysql:8.3
        environment:
            MYSQL_DATABASE: main_db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: rootpassword
        ports:
            - "3306:3306"
        volumes:
            - sql-data:/var/lib/mysql
        restart: unless-stopped
        networks:
            - app

    redis:
        image: redis:7.2.3
        command: redis-server /etc/redis/redis.conf
        ports:
            - 6379:6379
        volumes:
            - ./redis/redis.conf:/etc/redis/redis.conf
        restart: unless-stopped
        networks:
            - app

    kafka:
        image: wurstmeister/kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            resources:
                limits:
                    cpus: "1.0"
        restart: unless-stopped
        networks:
            - app
        depends_on:
            - zookeeper

    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
        networks:
            - app

    elasticsearch:
        image: elasticsearch:8.10.1
        volumes:
            - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        environment:
            - "discovery.type=single-node"
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        deploy:
            resources:
                limits:
                    cpus: "1.0"
        ports:
            - 9200:9200
            - 9300:9300
        restart: unless-stopped
        networks:
            - app

    prometheus:
        image: prom/prometheus
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090
        restart: unless-stopped
        networks:
            - app

networks:
    app:
        driver: bridge

volumes:
    sql-data:
    main-service-vendor:
