# Generated by Django 5.0.4 on 2024-04-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('media_url', models.URLField(blank=True, null=True)),
                ('entity_type', models.CharField(choices=[('user', 'User'), ('team', 'Team')], max_length=4)),
                ('entity_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
